### ISSUE TITLE
can't authentificate with gitlab registry

### ISSUE THREAD

**Issue by mqu** [deitch/docker_registry2#14]
hello,

I very happy to discover this nice ruby library for Docker Registry. I am trying to connect to a private gitlab registry either to public gitlab. I am facing to an exception ; I have no error with official Docker Hub. 

for debug purpose, I have added some debug traces (puts, pp).

best regards, Marc.

```bash
quinton@mydomain.fr:~/Bureau/perso/dev/ruby/gitlab/registry$ ruby test.rb 
trying to connect to https://registry.gitlab.com
#<URI::HTTPS https://registry.gitlab.com>
"registry.gitlab.com"
nil
nil
{:user=>"mqu", :password=>"XXXXXXX"}
doreq(get, /v2/);
rescue in doreq()
401 Unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

"bearer"
in do_bearer_req(get,/v2/);
"Bearer realm=\"https://gitlab.com/jwt/auth\",service=\"container_registry\""
{:params=>{"service"=>"container_registry"},
 :realm=>"https://gitlab.com/jwt/auth"}
"https://gitlab.com/jwt/auth"
/usr/lib/ruby/vendor_ruby/restclient/abstract_response.rb:74:in `return!': 403 Forbidden (RestClient::Forbidden)
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:495:in `process_result'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:421:in `block in transmit'
	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:413:in `transmit'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:176:in `execute'
	from /usr/lib/ruby/vendor_ruby/restclient/request.rb:41:in `execute'
	from /usr/lib/ruby/vendor_ruby/restclient.rb:65:in `get'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:217:in `authenticate_bearer'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:181:in `do_bearer_req'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:152:in `rescue in doreq'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:131:in `doreq'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:25:in `doget'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:37:in `ping'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/registry/registry.rb:21:in `initialize'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/docker_registry2.rb:9:in `new'
	from /home/quinton/Bureau/perso/dev/ruby/gitlab/registry/lib/docker_registry2.rb:9:in `connect'
	from test.rb:41:in `<main>'
quinton@mydomain.fr:~/Bureau/perso/dev/ruby/gitlab/registry$ ruby test.rb 
trying to connect to https://registry.hub.docker.com
#<URI::HTTPS https://registry.hub.docker.com>
"registry.hub.docker.com"
nil
nil
{:user=>"mqu31", :password=>"XXXXXXX"}
doreq(get, /v2/);
rescue in doreq()
401 Unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

"bearer"
in do_bearer_req(get,/v2/);
"Bearer realm=\"https://auth.docker.io/token\",service=\"registry.docker.io\""
{:params=>{"service"=>"registry.docker.io"},
 :realm=>"https://auth.docker.io/token"}
"https://auth.docker.io/token"
"eyJhb....Gw"
"{}"
#<DockerRegistry2::Registry:0x00558bda5957e8
 @base_uri="https://registry.hub.docker.com:443",
 @password=nil,
 @uri=#<URI::HTTPS https://registry.hub.docker.com>,
 @user=nil>
```

here is my ruby test code.

```ruby
require 'pp'
require './lib/docker_registry2.rb'

test=:docker_hub
# test=:gitlab
# test=:gitlab_private

case test

	when :docker_hub
		opts={
		 :user => 'mqu31',
		 :password => 'XXXXXXX'
		}
		url='https://registry.hub.docker.com'
		reg = DockerRegistry2.connect(url, opts)
		pp reg

	when :gitlab_private
		opts={
		 :user => 'marc.quinton',
		 :password => 'XXXXXXXX'
		}
		url='https://registry.private.fr'
		reg = DockerRegistry2.connect(url, opts)
		pp reg

	when :gitlab
		opts={
		 :user => 'mqu',
		 :password => 'XXXXXXX'
		}
		url='https://registry.gitlab.com'
		reg = DockerRegistry2.connect(url, opts)
		pp reg

end
```

**Comment by deitch** [comment]
Looks like gitlab uses a somewhat different protocol? Would be nice to see some docs from them on how they implement it. 

There are 3 steps:

1. Make request from registry, get `401` error with appropriate `www-authenticate` header. This part looks correct.
2. Authenticate against the server provided by the header, get back token
3. Make request from registry with token in header

It is doing step 1 correctly, but seems to be failing at step 2. There are a number of possibilities:

1. Your credentials are incorrect.
2. There is a bug in their header from step 1
3. There is a bug in their processing creds in step 2
4. There is some change in how you process the creds of which we are unaware.

You are sure creds are correct?

**Comment by deitch** [comment]
OK, one step up. If you encode it in the URL, it works fine. `https://username:password@registry.gitlab.com/`

So to check opts...

**Comment by deitch** [comment]
Uh, `connect()` only supports one var, the `uri`. How do you even pass in `opts` without getting an error: 

```
2.2.5 :013 > reg = DockerRegistry2.connect(url,opts)
ArgumentError: wrong number of arguments (2 for 0..1)
```

Makes sense to add it, but still...

**Comment by deitch** [comment]
Closed via https://github.com/deitch/docker_registry2/pull/15
