### ISSUE TITLE
Cannot connect with Basic Auth

### ISSUE THREAD

**Issue by johnsudaar** [deitch/docker_registry2#2]
The gem return an `undefined method 'gsub' for nil:NilClass` exception when using BasicAuth.

Stack trace : 

```
docker_registry2 (0.1.0) lib/registry/registry.rb:75:in `block in split_auth_header'
docker_registry2 (0.1.0) lib/registry/registry.rb:68:in `each'
docker_registry2 (0.1.0) lib/registry/registry.rb:68:in `split_auth_header'
docker_registry2 (0.1.0) lib/registry/registry.rb:46:in `authenticate'
docker_registry2 (0.1.0) lib/registry/registry.rb:32:in `rescue in doget'
docker_registry2 (0.1.0) lib/registry/registry.rb:19:in `doget'
docker_registry2 (0.1.0) lib/registry/registry.rb:82:in `ping'
docker_registry2 (0.1.0) lib/registry/registry.rb:15:in `initialize'
docker_registry2 (0.1.0) lib/docker_registry2.rb:8:in `new'
docker_registry2 (0.1.0) lib/docker_registry2.rb:8:in `connect'
 ...
```

**Comment by deitch** [comment]
Can you post the exact Ruby commands you used to get this to work (obviously, replace user/pass with fake ones)?

**Comment by deitch** [comment]
Never mind, I just saw your PR. Nice.
